server {
    listen 1010;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;
}
